export enum ROUTES {
  HOME = '/',
  LOGIN = '/login',
  REGISTER = '/register',
  OTP = '/otp',
  MAPS = '/operations/maps',
  ROBOTS = '/operations/robots',
  CLEANING_TASKS = '/operations/cleaning-tasks',
  LIVE_MONITORING = '/operations/live-monitoring',
  FLEETS = '/management/fleets',
  SCHEDULES = '/management/schedules',
  INCIDENTS = '/management/incidents',
  USERS = '/organization/users',
  ROLES_AND_PERMISSIONS = '/organization/roles-permissions',
  AUDIT_LOGS = '/organization/audit-logs',
  TENANT_SETTINGS = '/settings/tenant-settings',
}
